title:            Khalid's Portfolio
description:      A website where I share my porjects, blogs and resume

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:              images/icons8-code-fork-100.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://kalibrahim.github.io

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Notebook'
    url: '/finding_donors.html'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Favorites'
    url: '#'
    submenu:
      - title: 'Code Highlighter'
        url: '/intro/code-highlighting-post/'
      - title: 'Sample Post'
        url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Khalid Al Ibrahim
  site:           https://kalibrahim.github.io/
  avatar:         images/IMG_0309.jpg
  bio:            "An aspiring data scientist. My passion for technology drives me to learn, create and innovate."
  email:          kalibrahim94@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: KhalidAlIbrahi5 # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: kalibrahim

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/kalibrahim"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/kalibrah/"


# Background image to be tiled on all pages
background: images/paul-frenzel-159408-unsplash.jpg

# Analytics and webmaster tools stuff goes here
google_analytics: UA-122986975-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Qatar
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 10

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
# theme: neo-hpstr-jekyll-theme
